### ISSUE TITLE
Add space around of !

### ISSUE THREAD

**Issue by natanfelles** [louisl/CodeIgniter4-Standard#13]
```php
if ( ! file_exists($filename))
{
    //
}
```

**Comment by louisl** [comment]
Hi @natanfelles,

When I started this, I based some rules on consistency in the majority of the code, there was no requirement for a space before a 'boolean not' in the [CodeIgniter 4 style guide](https://bcit-ci.github.io/CodeIgniter4/contributing/styleguide.html?highlight=concatenation#logical-operators) either, it does however indicate there should be a space after. I realise this differs to the [CodeIgniter 3 style guide](https://www.codeigniter.com/user_guide/general/styleguide.html#logical-operators) and I think as we're moving forward with a completely new version we can eliminate some of those CodeIgniter 3 oddities. If @jim-parry or @lonnieezell instruct me otherwise I'll change it, no problem.

So the CodeIgniter 4 syntax at the moment which the standard checks for is:

```php
if (! file_exists($filename))
{
    //
}
```

**Comment by lonnieezell** [comment]
@louisl the way you've got it working currently is the preferred way.

Just realized @jim-parry hasn't moved this over to the official repo, yet, has he?

**Comment by louisl** [comment]
@lonnieezell Thanks for the confirmation.

I haven't heard anything for a quite some time, but that's suited me to be honest, I've been very busy with the day job these last few months. I can see a few users are using the standard but it's not "out there" yet looking at the CI4 source code. 

I've been working on another standard and have that working in a Travis CI build to check the source of some projects we're doing on pull requests. So when @jim-parry and yourself are ready to make it part of the pull request process I'll be able to help with the Travis set-up.

It'll flag up a ton of stuff at the moment though and I guess there's probably quite a few forks being worked on so I'm not sure if you want to implement it just yet.

**Comment by jim-parry** [comment]
@louisl It looks like the process to transfer the repo would be
- add me as a maintainer to your repo
- I can transfer it to bcit-ci
- you retain maintainer rights on the transferred repo

packagist.org will need updating, with the new github repo link too

I will make an announcement on our forum once this is done :)

**Comment by natanfelles** [comment]
Closing, thanks!
